const token = process.env.SUPABASE_TOKEN;
const ref = "fvkghxqzjcqewbqmnopy";

const blockedWords = [
  "vai tomar no cu", "vai tomar no cú",
  "cu", "cú", "cuzão", "cuzinho",
  "boceta", "buceta",
  "viado", "veado",
  "vaca",
  "galinha",
  "piranha",
  "biscate",
  "olho de porco",
  "pinto", "pênis", "penis",
  "brioco",
  "boguinha",
  "anel de couro",
  "arrombado",
  "fdp", "filho da puta",
];

const sql = `
CREATE EXTENSION IF NOT EXISTS unaccent;

CREATE TABLE IF NOT EXISTS blocked_words (
  id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  word text NOT NULL
);

TRUNCATE blocked_words;

${blockedWords.map(w => {
  // escape single quotes in the word
  const escaped = w.replace(/'/g, "''");
  return `INSERT INTO blocked_words (word) VALUES (LOWER(unaccent('${escaped}')));`;
}).join("\n")}

CREATE OR REPLACE FUNCTION check_blocked_word()
RETURNS trigger AS $$
DECLARE
  normalized text;
  bw record;
BEGIN
  normalized := LOWER(unaccent(NEW.content));
  FOR bw IN SELECT word FROM blocked_words LOOP
    IF normalized LIKE '%' || bw.word || '%' THEN
      RAISE EXCEPTION 'Mensagem contém palavra/frase bloqueada';
    END IF;
  END LOOP;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS trg_check_blocked_word ON messages;

CREATE TRIGGER trg_check_blocked_word
  BEFORE INSERT ON messages
  FOR EACH ROW
  EXECUTE FUNCTION check_blocked_word();
`;

const endpoints = [
  `https://api.supabase.com/v1/projects/${ref}/database/query`,
  `https://api.supabase.com/v1/projects/${ref}/sql`,
];

for (const url of endpoints) {
  const r = await fetch(url, {
    method: "POST",
    headers: {
      Authorization: `Bearer ${token}`,
      "Content-Type": "application/json",
    },
    body: JSON.stringify({ query: sql }),
  });

  if (r.ok) {
    console.log("Tabela 'blocked_words', trigger e words cadastrados com sucesso.");
    process.exit(0);
  }

  const text = await r.text();
  if (url === endpoints[endpoints.length - 1]) {
    console.error("Erro:", text);
    process.exit(1);
  }
}
