const token = process.env.SUPABASE_TOKEN;
const ref = "fvkghxqzjcqewbqmnopy";

// Realistic player data per team: [name, position, shirt_number]
// 3 GK, 8 DF, 6 MF, 6 FW per team = 23 players

const squads = {
  MEX: [
    ["Guillermo Ochoa","GK",1],["Carlos Acevedo","GK",13],["Luis Malagón","GK",23],
    ["Jorge Sánchez","DF",2],["César Montes","DF",3],["Johan Vásquez","DF",5],
    ["Gerardo Arteaga","DF",6],["Julián Araujo","DF",19],["Israel Reyes","DF",20],
    ["Jesús Gallardo","DF",21],["Kevin Álvarez","DF",26],
    ["Edson Álvarez","MF",4],["Luis Chávez","MF",7],["Carlos Rodríguez","MF",8],
    ["Sebastián Córdova","MF",10],["Andrés Guardado","MF",14],["Erick Sánchez","MF",15],
    ["Raúl Jiménez","FW",9],["Santiago Giménez","FW",11],["Orbelín Pineda","FW",16],
    ["César Huerta","FW",17],["Guillermo Martínez","FW",12],["Roberto Alvarado","FW",18],
  ],
  KOR: [
    ["Kim Seung-gyu","GK",1],["Jo Hyeon-woo","GK",12],["Song Bum-keun","GK",21],
    ["Kim Min-jae","DF",4],["Kim Young-gwon","DF",19],["Lee Ki-je","DF",3],
    ["Seol Young-woo","DF",2],["Kim Ji-soo","DF",15],["Kim Won-gyun","DF",23],
    ["Kim Ju-sung","DF",20],["Park Jin-sub","DF",22],
    ["Lee Kang-in","MF",7],["Hwang Hee-chan","MF",11],["Son Heung-min","MF",10],
    ["Lee Jae-sung","MF",6],["Park Yong-woo","MF",5],["Hong Hyun-seok","MF",14],
    ["Cho Gue-sung","FW",9],["Hwang Ui-jo","FW",16],["Oh Hyeon-gyu","FW",17],
    ["Jeong Woo-yeong","FW",13],["Yang Hyun-jun","FW",8],["Bae Jun-ho","FW",18],
  ],
  CZE: [
    ["Tomáš Vaclík","GK",1],["Jindřich Staněk","GK",12],["Vítězslav Jaroš","GK",23],
    ["Ladislav Krejčí","DF",3],["David Zima","DF",4],["Tomáš Holeš","DF",5],
    ["Jaroslav Zelený","DF",6],["Vladimír Coufal","DF",2],["David Douděra","DF",22],
    ["Jan Bořil","DF",15],["Patrizio Stronati","DF",18],
    ["Tomáš Souček","MF",8],["Antonín Barák","MF",10],["Michal Sadílek","MF",7],
    ["Alex Král","MF",11],["Lukáš Provod","MF",14],["Ondřej Lingr","MF",16],
    ["Patrik Schick","FW",9],["Adam Hložek","FW",13],["Jan Kuchta","FW",17],
    ["Mojmír Chytil","FW",19],["Matěj Jurásek","FW",20],["Václav Černý","FW",21],
  ],
  RSA: [
    ["Ronwen Williams","GK",1],["Bruce Bvuma","GK",12],["Ricardo Goss","GK",23],
    ["Nyiko Mobbie","DF",2],["Mothobi Mvala","DF",4],["Siyabonga Ngezana","DF",5],
    ["Lyle Lakay","DF",3],["Thapelo Morena","DF",6],["Terrence Mashego","DF",14],
    ["Malebogo Modise","DF",20],["Nkosinathi Sibisi","DF",22],
    ["Teboho Mokoena","MF",8],["Sphephelo Sithole","MF",10],["Goodman Mosele","MF",15],
    ["Luke Le Roux","MF",13],["Ethan Brooks","MF",17],["Cole Alexander","MF",19],
    ["Lyle Foster","FW",9],["Percy Tau","FW",11],["Themba Zwane","FW",7],
    ["Evidence Makgopa","FW",16],["Zakhele Lepasa","FW",18],["Oswin Appollis","FW",21],
  ],
  CAN: [
    ["Milan Borjan","GK",1],["Dayne St. Clair","GK",12],["Maxime Crépeau","GK",23],
    ["Alistair Johnston","DF",2],["Kamal Miller","DF",4],["Steven Vitória","DF",5],
    ["Sam Adekugbe","DF",3],["Richie Laryea","DF",6],["Derek Cornelius","DF",14],
    ["Zachary Brault-Guillard","DF",22],["Dominick Zator","DF",15],
    ["Stephen Eustáquio","MF",8],["Jonathan Osorio","MF",10],["Ismaël Koné","MF",7],
    ["Samuel Piette","MF",11],["Mathieu Choinière","MF",13],["Liam Fraser","MF",16],
    ["Jonathan David","FW",9],["Cyle Larin","FW",17],["Tajon Buchanan","FW",19],
    ["Liam Millar","FW",18],["Jacen Russell-Rowe","FW",20],["Iké Ugbo","FW",21],
  ],
  SUI: [
    ["Yann Sommer","GK",1],["Gregor Kobel","GK",12],["Jonas Omlin","GK",23],
    ["Ricardo Rodríguez","DF",5],["Manuel Akanji","DF",4],["Nico Elvedi","DF",3],
    ["Silvan Widmer","DF",2],["Denis Zakaria","DF",6],["Kevin Mbabu","DF",19],
    ["Cédric Zesiger","DF",15],["Eray Cömert","DF",22],
    ["Granit Xhaka","MF",10],["Remo Freuler","MF",8],["Xherdan Shaqiri","MF",7],
    ["Michel Aebischer","MF",14],["Djibril Sow","MF",16],["Fabian Rieder","MF",20],
    ["Breel Embolo","FW",9],["Noah Okafor","FW",11],["Ruben Vargas","FW",17],
    ["Zeki Amdouni","FW",18],["Dan Ndoye","FW",21],["Cedric Itten","FW",13],
  ],
  QAT: [
    ["Meshaal Barsham","GK",1],["Saad Al-Sheeb","GK",12],["Yousuf Hassan","GK",23],
    ["Ro-Ro","DF",2],["Abdelkarim Hassan","DF",3],["Tarek Salman","DF",4],
    ["Almoez Ali","DF",5],["Lucas Mendes","DF",15],["Musab Kheder","DF",13],
    ["Bassam Al-Rawi","DF",14],["Jassem Gaber","DF",16],
    ["Hassan Al-Haydos","MF",10],["Ahmed Fatehi","MF",6],["Abdulaziz Hatem","MF",8],
    ["Mohammed Waad","MF",7],["Ali Assadalla","MF",9],["Mostafa Meshaal","MF",11],
    ["Karim Boudiaf","MF",17],["Ismaeel Mohammad","FW",20],
    ["Ahmed Alaaeldin","FW",18],["Yusuf Abdurisag","FW",21],
    ["Abdullah Al-Ahrak","FW",19],["Khalid Muneer","FW",22],
  ],
  BIH: [
    ["Ibrahim Šehić","GK",1],["Nikola Vasilj","GK",12],["Kenan Pirić","GK",23],
    ["Sead Kolašinac","DF",5],["Dennis Hadžikadunić","DF",4],["Jusuf Gazibegović","DF",3],
    ["Amar Dedić","DF",2],["Nihad Mujakić","DF",6],["Adrián Leon Barišić","DF",15],
    ["Ermin Bičakčić","DF",19],["Haris Alihodžić","DF",22],
    ["Miralem Pjanić","MF",8],["Rade Krunić","MF",10],["Benjamin Tahirović","MF",7],
    ["Miroslav Stevanović","MF",14],["Denis Huseinbašić","MF",16],["Gojko Cimirot","MF",20],
    ["Edin Džeko","FW",11],["Ermedin Demirović","FW",9],["Dario Vujičević","FW",17],
    ["Haris Hajdarević","FW",18],["Belmin Dizdarević","FW",21],["Admir Bristrić","FW",13],
  ],
  BRA: [
    ["Alisson","GK",1],["Ederson","GK",12],["Bento","GK",23],
    ["Danilo","DF",2],["Éder Militão","DF",4],["Marquinhos","DF",3],
    ["Gabriel Magalhães","DF",5],["Renan Lodi","DF",6],["Yan Couto","DF",13],
    ["Bremer","DF",14],["Murilo","DF",15],
    ["Casemiro","MF",8],["Bruno Guimarães","MF",7],["Lucas Paquetá","MF",10],
    ["João Gomes","MF",16],["Douglas Luiz","MF",18],["André","MF",17],
    ["Vinícius Júnior","FW",11],["Rodrygo","FW",9],["Raphinha","FW",19],
    ["Gabriel Jesus","FW",20],["Endrick","FW",21],["Matheus Cunha","FW",22],
  ],
  HAI: [
    ["Johny Placide","GK",1],["Josué Duverger","GK",12],["Alexandre Pierre","GK",23],
    ["Martin Expérience","DF",2],["Ricardo Adé","DF",4],["Alex Junior","DF",5],
    ["Francois Dulysse","DF",3],["Carlens Arcus","DF",6],["Zachary Brault-Guillard","DF",14],
    ["Djimy Alexis","DF",22],["Bendjy Estama","DF",15],
    ["Bryan Alceus","MF",8],["Dutherson Clerveaux","MF",10],["Jeff Louis","MF",7],
    ["Charles Hérold Jr.","MF",11],["Danley Jean-Jacques","MF",13],["Peterson Joseph","MF",16],
    ["Duckens Nazon","FW",9],["Frédéric Piquion","FW",17],["Carnejy Antoine","FW",19],
    ["Derrick Etienne","FW",18],["Ronaldo Damus","FW",20],["Christoffer Mfé","FW",21],
  ],
  MAR: [
    ["Yassine Bounou","GK",1],["Munir Mohamedi","GK",12],["Youssef Benali","GK",23],
    ["Achraf Hakimi","DF",2],["Noussair Mazraoui","DF",3],["Romain Saïss","DF",5],
    ["Nayef Aguerd","DF",4],["Yahia Attiyat Allah","DF",6],["Chadi Riad","DF",13],
    ["Abdel Abqar","DF",14],["Yahya Berrahma","DF",15],
    ["Sofyan Amrabat","MF",8],["Azzedine Ounahi","MF",10],["Ismaël Saibari","MF",7],
    ["Bilal El Khannous","MF",11],["Amine Harit","MF",16],["Oussama Targhalline","MF",18],
    ["Hakim Ziyech","FW",9],["Sofiane Boufal","FW",17],["Ayoub El Kaabi","FW",19],
    ["Elye Wahi","FW",20],["Abde Ezzalzouli","FW",21],["Youssef En-Nesyri","FW",22],
  ],
  SCO: [
    ["Angus Gunn","GK",1],["Liam Kelly","GK",12],["Zander Clark","GK",23],
    ["Andy Robertson","DF",3],["Kieran Tierney","DF",5],["Grant Hanley","DF",4],
    ["Jack Hendry","DF",2],["Anthony Ralston","DF",6],["Nathan Patterson","DF",13],
    ["Liam Cooper","DF",15],["John Souttar","DF",14],
    ["Scott McTominay","MF",8],["John McGinn","MF",7],["Callum McGregor","MF",10],
    ["Billy Gilmour","MF",11],["Ryan Christie","MF",16],["Kenny McLean","MF",17],
    ["Che Adams","FW",9],["Lawrence Shankland","FW",18],["James Forrest","FW",19],
    ["Ryan Fraser","FW",20],["Kevin Nisbet","FW",21],["Lyndon Dykes","FW",22],
  ],
  USA: [
    ["Matt Turner","GK",1],["Ethan Horvath","GK",12],["Gabriel Slonina","GK",23],
    ["Sergiño Dest","DF",2],["Chris Richards","DF",4],["Tim Ream","DF",5],
    ["Antonee Robinson","DF",3],["Joe Scally","DF",6],["Auston Trusty","DF",13],
    ["Cameron Carter-Vickers","DF",14],["Miles Robinson","DF",15],
    ["Weston McKennie","MF",8],["Tyler Adams","MF",10],["Giovanni Reyna","MF",7],
    ["Yunus Musah","MF",11],["Christian Pulisic","MF",9],["Luca de la Torre","MF",16],
    ["Folarin Balogun","FW",17],["Ricardo Pepi","FW",18],["Tim Weah","FW",19],
    ["Brenden Aaronson","FW",20],["Haji Wright","FW",21],["Cade Cowell","FW",22],
  ],
  PAR: [
    ["Carlos Coronel","GK",1],["Antony Silva","GK",12],["Juan Espínola","GK",23],
    ["Gustavo Gómez","DF",2],["Junior Alonso","DF",3],["Omar Alderete","DF",4],
    ["Matías Espinoza","DF",5],["Robert Rojas","DF",6],["Alberto Espínola","DF",13],
    ["Iván Piris","DF",14],["Jorge Morel","DF",15],
    ["Édgar Cardozo","MF",8],["Mathías Villasanti","MF",7],["Alejandro Romero","MF",10],
    ["Hugo Cuenca","MF",11],["Richard Sánchez","MF",16],["Ángel Cardozo","MF",17],
    ["Miguel Almirón","FW",9],["Derlis González","FW",18],["Ramón Sosa","FW",19],
    ["Gabriel Ávalos","FW",20],["Antonio Sanabria","FW",21],["Óscar Cardozo","FW",22],
  ],
  TUR: [
    ["Mert Günok","GK",1],["Uğurcan Çakır","GK",12],["Altay Bayındır","GK",23],
    ["Çağlar Söyüncü","DF",2],["Abdülkerim Bardakcı","DF",4],["Ozan Kabak","DF",5],
    ["Ferdi Kadıoğlu","DF",3],["Zeki Çelik","DF",6],["Merih Demiral","DF",13],
    ["Samet Akaydin","DF",14],["Cenk Özkacar","DF",15],
    ["Hakan Çalhanoğlu","MF",10],["Orkun Kökçü","MF",8],["Salih Özcan","MF",7],
    ["İsmail Yüksek","MF",11],["Arda Güler","MF",16],["Can Uzun","MF",17],
    ["Kerem Aktürkoğlu","FW",9],["Yusuf Yazıcı","FW",18],["Kerem Demirbay","FW",19],
    ["Barış Alper Yılmaz","FW",20],["Enes Ünal","FW",21],["Cenk Tosun","FW",22],
  ],
  AUS: [
    ["Mathew Ryan","GK",1],["Andrew Redmayne","GK",12],["Joe Gauci","GK",23],
    ["Milos Degenek","DF",2],["Harry Souttar","DF",4],["Kye Rowles","DF",5],
    ["Aziz Behich","DF",3],["Lewis Miller","DF",6],["Jason Geria","DF",13],
    ["Cameron Burgess","DF",14],["Ryan Strain","DF",15],
    ["Aaron Mooy","MF",8],["Jackson Irvine","MF",7],["Riley McGree","MF",10],
    ["Keanu Baccus","MF",11],["Aiden O'Neill","MF",16],["Connor Metcalfe","MF",17],
    ["Mitchell Duke","FW",9],["Mathew Leckie","FW",18],["Garang Kuol","FW",19],
    ["Martin Boyle","FW",20],["Bruno Fornaroli","FW",21],["Adam Taggart","FW",22],
  ],
  GER: [
    ["Manuel Neuer","GK",1],["Marc-André ter Stegen","GK",12],["Alexander Nübel","GK",23],
    ["Joshua Kimmich","DF",2],["Antonio Rüdiger","DF",4],["Jonathan Tah","DF",5],
    ["David Raum","DF",3],["Benjamin Henrichs","DF",6],["Nico Schlotterbeck","DF",13],
    ["Robin Koch","DF",14],["Malick Thiaw","DF",15],
    ["İlkay Gündoğan","MF",8],["Jamal Musiala","MF",7],["Toni Kroos","MF",10],
    ["Florian Wirtz","MF",11],["Robert Andrich","MF",16],["Pascal Groß","MF",17],
    ["Leroy Sané","FW",9],["Kai Havertz","FW",18],["Serge Gnabry","FW",19],
    ["Niclas Füllkrug","FW",20],["Karim Adeyemi","FW",21],["Jonathan Burkardt","FW",22],
  ],
  ECU: [
    ["Hernán Galíndez","GK",1],["Moisés Ramírez","GK",12],["Jorge Pinos","GK",23],
    ["Piero Hincapié","DF",2],["Félix Torres","DF",3],["Willian Pacho","DF",4],
    ["Ángelo Preciado","DF",5],["Pervis Estupiñán","DF",6],["Jhon Espinoza","DF",13],
    ["Jackson Porozo","DF",14],["Leonardo Realpe","DF",15],
    ["Moisés Caicedo","MF",8],["Alan Franco","MF",7],["Carlos Gruezo","MF",10],
    ["Jeremy Sarmiento","MF",11],["Joao Ortiz","MF",16],["José Cifuentes","MF",17],
    ["Enner Valencia","FW",9],["Kevin Rodríguez","FW",18],["Ángel Mena","FW",19],
    ["Jhon Jairo Cifuentes","FW",20],["Kendry Páez","FW",21],["Marcos López","FW",22],
  ],
  CIV: [
    ["Yahia Fofana","GK",1],["Badra Ali Sangaré","GK",12],["Charles Ayayi","GK",23],
    ["Serge Aurier","DF",2],["Odilon Kossounou","DF",3],["Evan Ndicka","DF",4],
    ["Willy Boly","DF",5],["Ghislain Konan","DF",6],["Emmanuel Agbadou","DF",13],
    ["Wilfried Singo","DF",14],["Kouadio-Yves Dabila","DF",15],
    ["Franck Kessié","MF",8],["Seko Fofana","MF",7],["Jean Seri","MF",10],
    ["Hamed Traorè","MF",11],["Christian Kouamé","MF",16],["Max Gradel","MF",17],
    ["Sébastien Haller","FW",9],["Nicolas Pépé","FW",18],["Jonathan Bamba","FW",19],
    ["Wílfried Zaha","FW",20],["Karim Konaté","FW",21],["Simon Adingra","FW",22],
  ],
  CUW: [
    ["Eloy Room","GK",1],["Tyrick Bodak","GK",12],["Tristan van der Meer","GK",23],
    ["Cuco Martina","DF",2],["Darryl Lachman","DF",3],["Jurich Carolina","DF",4],
    ["Rhu-Endly Aurelius","DF",5],["Justin Ogenia","DF",6],["Kevin Felida","DF",13],
    ["Gilliano Wijnaldum","DF",14],["Richeldo Olfers","DF",15],
    ["Leandro Bacuna","MF",8],["Daniël van Kaam","MF",7],["Vurnon Anita","MF",10],
    ["Gersinio Constancia","MF",11],["Kenji Gorré","MF",16],["Nathangelo Marcellina","MF",17],
    ["Rangelo Janga","FW",9],["Charlison Benschop","FW",18],["Jeremy Antonisse","FW",19],
    ["Richairo Zivkovic","FW",20],["Jafar Arias","FW",21],["Xander Severina","FW",22],
  ],
  NED: [
    ["Justin Bijlow","GK",1],["Mark Flekken","GK",12],["Bart Verbruggen","GK",23],
    ["Virgil van Dijk","DF",4],["Nathan Aké","DF",5],["Denzel Dumfries","DF",2],
    ["Daley Blind","DF",3],["Micky van de Ven","DF",6],["Matthijs de Ligt","DF",13],
    ["Stefan de Vrij","DF",14],["Lutsharel Geertruida","DF",15],
    ["Frenkie de Jong","MF",8],["Tijjani Reijnders","MF",7],["Mats Wieffer","MF",10],
    ["Xavi Simons","MF",11],["Teun Koopmeiners","MF",16],["Joey Veerman","MF",17],
    ["Memphis Depay","FW",9],["Cody Gakpo","FW",18],["Donyell Malen","FW",19],
    ["Brian Brobbey","FW",20],["Steven Bergwijn","FW",21],["Wout Weghorst","FW",22],
  ],
  JPN: [
    ["Kosuke Nakamura","GK",1],["Keisuke Osako","GK",12],["Zion Suzuki","GK",23],
    ["Takehiro Tomiyasu","DF",2],["Ko Itakura","DF",4],["Hiroki Ito","DF",5],
    ["Yuta Nakayama","DF",3],["Ritsu Doan","DF",6],["Shogo Taniguchi","DF",13],
    ["Tsuyoshi Watanabe","DF",14],["Koki Machida","DF",15],
    ["Wataru Endo","MF",8],["Daichi Kamada","MF",7],["Takefusa Kubo","MF",10],
    ["Ao Tanaka","MF",11],["Hidemasa Morita","MF",16],["Kaoru Mitoma","MF",17],
    ["Kyogo Furuhashi","FW",9],["Ayase Ueda","FW",18],["Takumi Minamino","FW",19],
    ["Keito Nakamura","FW",20],["Mao Hosoya","FW",21],["Koki Ogawa","FW",22],
  ],
  SWE: [
    ["Robin Olsen","GK",1],["Kristoffer Nordfeldt","GK",12],["Viktor Johansson","GK",23],
    ["Victor Lindelöf","DF",2],["Isak Hien","DF",4],["Ludwig Augustinsson","DF",5],
    ["Emil Krafth","DF",3],["Gabriel Gudmundsson","DF",6],["Joseph Okumu","DF",13],
    ["Ken Sema","DF",14],["Joel Andersson","DF",15],
    ["Dejan Kulusevski","MF",8],["Emil Forsberg","MF",7],["Mattias Svanberg","MF",10],
    ["Jens Cajuste","MF",11],["Hugo Larsson","MF",16],["Samuel Gustafson","MF",17],
    ["Alexander Isak","FW",9],["Viktor Gyökeres","FW",18],["Anthony Elanga","FW",19],
    ["Jesper Karlström","FW",20],["Marcus Rohdén","FW",21],["Jacob Ondrejka","FW",22],
  ],
  TUN: [
    ["Bechir Ben Saïd","GK",1],["Aymen Dahmen","GK",12],["Moez Ben Cherifia","GK",23],
    ["Montassar Talbi","DF",2],["Ali Abdi","DF",3],["Nader Ghandri","DF",4],
    ["Bilel Ifa","DF",5],["Wajdi Kechrida","DF",6],["Mohamed Dräger","DF",13],
    ["Hamza Mathlouthi","DF",14],["Yassine Meriah","DF",15],
    ["Aïssa Laïdouni","MF",8],["Ellyes Skhiri","MF",7],["Ferjani Sassi","MF",10],
    ["Bassem Srarfi","MF",11],["Ali Maâloul","MF",16],["Hannibal Mejbri","MF",17],
    ["Seifeddine Jaziri","FW",9],["Taha Yassine Khenissi","FW",18],
    ["Youssef Msakni","FW",19],["Elias Achouri","FW",20],
    ["Mohamed Ali Ben Romdhane","FW",21],["Haythem Jouini","FW",22],
  ],
  BEL: [
    ["Thibaut Courtois","GK",1],["Koen Casteels","GK",12],["Matz Sels","GK",23],
    ["Wout Faes","DF",2],["Jan Vertonghen","DF",4],["Arthur Theate","DF",5],
    ["Timothy Castagne","DF",3],["Zeno Debast","DF",6],["Maxim De Cuyper","DF",13],
    ["Koni De Winter","DF",14],["Brandon Mechele","DF",15],
    ["Kevin De Bruyne","MF",8],["Youri Tielemans","MF",7],["Orel Mangala","MF",10],
    ["Amadou Onana","MF",11],["Hans Vanaken","MF",16],["Jérémy Doku","MF",17],
    ["Romelu Lukaku","FW",9],["Lois Openda","FW",18],["Leandro Trossard","FW",19],
    ["Johan Bakayoko","FW",20],["Dodi Lukebakio","FW",21],["Michy Batshuayi","FW",22],
  ],
  IRN: [
    ["Alireza Biranvand","GK",1],["Payam Niazmand","GK",12],["Amir Abedzadeh","GK",23],
    ["Majid Hosseini","DF",2],["Shoja Khalilzadeh","DF",4],["Milad Mohammadi","DF",5],
    ["Ehsan Hajsafi","DF",3],["Sadegh Moharrami","DF",6],["Omid Noorafkan","DF",13],
    ["Ramin Rezaeian","DF",14],["Abolfazl Jalali","DF",15],
    ["Saeid Ezatolahi","MF",8],["Saman Ghoddos","MF",7],["Ahmad Nourollahi","MF",10],
    ["Mehdi Torabi","MF",11],["Ali Karimi","MF",16],["Mohammad Hosseini","MF",17],
    ["Mehdi Taremi","FW",9],["Sardar Azmoun","FW",18],["Alireza Jahanbakhsh","FW",19],
    ["Karim Ansarifard","FW",20],["Mohammad Mohebi","FW",21],["Shahriyar Moghanlou","FW",22],
  ],
  EGY: [
    ["Mohamed El Shenawy","GK",1],["Mohamed Abou Gabal","GK",12],["Mahdi Soliman","GK",23],
    ["Mohamed Abdelmonem","DF",2],["Ali Gabr","DF",4],["Ahmed Hegazy","DF",5],
    ["Omar Kamal","DF",3],["Yasser Ibrahim","DF",6],["Mohamed Hamdy","DF",13],
    ["Osama Galal","DF",14],["Ahmed Samy","DF",15],
    ["Mohamed Elneny","MF",8],["Hamdy Fathy","MF",7],["Emam Ashour","MF",10],
    ["Aliou Dieng","MF",11],["Marwan Attia","MF",16],["Sam Mohsen","MF",17],
    ["Mohamed Salah","FW",9],["Omar Marmoush","FW",18],["Mostafa Mohamed","FW",19],
    ["Ahmed Sayed","FW",20],["Mahmoud Trezeguet","FW",21],["Ibrahim Adel","FW",22],
  ],
  NZL: [
    ["Stefan Marinovic","GK",1],["Oliver Sail","GK",12],["Jamie Searle","GK",23],
    ["Michael Boxall","DF",2],["Nando Pijnaker","DF",4],["Tommy Smith","DF",5],
    ["Liberato Cacace","DF",3],["Dane Ingham","DF",6],["James McGarry","DF",13],
    ["Tyler Bindon","DF",14],["Kelvin Kalua","DF",15],
    ["Joe Bell","MF",8],["Ryan Thomas","MF",7],["Marko Stamenic","MF",10],
    ["Alex Rufer","MF",11],["Sarpreet Singh","MF",16],["Clayton Lewis","MF",17],
    ["Chris Wood","FW",9],["Jesse Randall","FW",18],["Elliot Collier","FW",19],
    ["Logan Rogerson","FW",20],["Max Mata","FW",21],["Ben Waine","FW",22],
  ],
  ESP: [
    ["Unai Simón","GK",1],["Álex Remiro","GK",12],["David Raya","GK",23],
    ["Dani Carvajal","DF",2],["Aymeric Laporte","DF",4],["Pau Torres","DF",5],
    ["Alejandro Balde","DF",3],["Robin Le Normand","DF",6],["Pedri","DF",13],
    ["Marc Cucurella","DF",14],["Jesús Navas","DF",15],
    ["Rodri","MF",8],["Pedri","MF",7],["Mikel Merino","MF",10],
    ["Fabián Ruiz","MF",11],["Martín Zubimendi","MF",16],["Aleix García","MF",17],
    ["Álvaro Morata","FW",9],["Lamine Yamal","FW",18],["Nico Williams","FW",19],
    ["Dani Olmo","FW",20],["Mikel Oyarzabal","FW",21],["Joselu","FW",22],
  ],
  URU: [
    ["Sergio Rochet","GK",1],["Franco Israel","GK",12],["Fernando Muslera","GK",23],
    ["José Giménez","DF",2],["Ronald Araújo","DF",4],["Mathías Olivera","DF",5],
    ["Nahitan Nández","DF",3],["Matías Viña","DF",6],["Sebastián Cáceres","DF",13],
    ["Bruno Méndez","DF",14],["Santiago Bueno","DF",15],
    ["Federico Valverde","MF",8],["Manuel Ugarte","MF",7],["Giorgian de Arrascaeta","MF",10],
    ["Rodrigo Bentancur","MF",11],["Emiliano Martínez","MF",16],["Felipe Carballo","MF",17],
    ["Darwin Núñez","FW",9],["Facundo Pellistri","FW",18],["Maximiliano Araújo","FW",19],
    ["Luciano Rodríguez","FW",20],["Cristian Olivera","FW",21],["Brian Rodríguez","FW",22],
  ],
  KSA: [
    ["Mohammed Al-Owais","GK",1],["Nawaf Al-Aqidi","GK",12],["Ahmed Al-Kassar","GK",23],
    ["Abdulelah Al-Amri","DF",2],["Ali Al-Bulayhi","DF",4],["Yasser Al-Shahrani","DF",5],
    ["Sultan Al-Ghannam","DF",3],["Mohammed Al-Burayk","DF",6],["Ahmed Bamsaud","DF",13],
    ["Hassan Al-Tambakti","DF",14],["Awn Al-Slaluli","DF",15],
    ["Mohamed Kanno","MF",8],["Sami Al-Najei","MF",7],["Salem Al-Shehri","MF",10],
    ["Salman Al-Faraj","MF",11],["Firas Al-Brikan","MF",16],["Abdulrahman Al-Obud","MF",17],
    ["Odah Khafaji","FW",9],["Fahad Al-Muwallad","FW",18],["Haitham Asiri","FW",19],
    ["Abdullah Al-Hamdan","FW",20],["Saleh Al-Abbas","FW",21],["Ali Al-Hassan","FW",22],
  ],
  CPV: [
    ["Josimar Dias","GK",1],["Bruno Varela","GK",12],["Márcio Rosa","GK",23],
    ["Carlos Ponck","DF",2],["Roberto Lopes","DF",4],["Logan Costa","DF",5],
    ["Stopira","DF",3],["Steven Moreira","DF",6],["Paulo Lopes","DF",13],
    ["Jeffry Fortes","DF",14],["Fidelis Varela","DF",15],
    ["Pedro Pires","MF",8],["Rui Mendes","MF",7],["Jamiro Monteiro","MF",10],
    ["Nenass","MF",11],["Kevin Oliveira","MF",16],["André Tavares","MF",17],
    ["Garry Rodrigues","FW",9],["Jordão Cardoso","FW",18],["Ryan Mendes","FW",19],
    ["Jovane Cabral","FW",20],["Gilson Tavares","FW",21],["Willy Semedo","FW",22],
  ],
  FRA: [
    ["Hugo Lloris","GK",1],["Alphonse Aréola","GK",12],["Mike Maignan","GK",23],
    ["Dayot Upamecano","DF",2],["Ibrahima Konaté","DF",4],["Lucas Hernández","DF",5],
    ["Theo Hernández","DF",3],["Jules Koundé","DF",6],["William Saliba","DF",13],
    ["Benjamin Pavard","DF",14],["Axel Disasi","DF",15],
    ["Aurélien Tchouaméni","MF",8],["Adrien Rabiot","MF",7],["Eduardo Camavinga","MF",10],
    ["Youssouf Fofana","MF",11],["Warren Zaïre-Emery","MF",16],["Khephren Thuram","MF",17],
    ["Kylian Mbappé","FW",9],["Antoine Griezmann","FW",18],["Ousmane Dembélé","FW",19],
    ["Randal Kolo Muani","FW",20],["Marcus Thuram","FW",21],["Olivier Giroud","FW",22],
  ],
  SEN: [
    ["Édouard Mendy","GK",1],["Mamadou Samba Diallo","GK",12],["Mory Diaw","GK",23],
    ["Kalidou Koulibaly","DF",2],["Abdou Diallo","DF",4],["Pape Abou Cissé","DF",5],
    ["Ismail Jakobs","DF",3],["Moussa Niakhaté","DF",6],["Fodé Ballo-Touré","DF",13],
    ["Ousseynou Basse","DF",14],["Moussa Sagnan","DF",15],
    ["Idrissa Gueye","MF",8],["Pathe Ciss","MF",7],["Nampalys Mendy","MF",10],
    ["Pape Gueye","MF",11],["Moustapha Name","MF",16],["Dion Lopy","MF",17],
    ["Sadio Mané","FW",9],["Ismaïla Sarr","FW",18],["Nicolas Jackson","FW",19],
    ["Boulaye Dia","FW",20],["Iliman Ndiaye","FW",21],["Habi Diallo","FW",22],
  ],
  NOR: [
    ["Ørjan Nyland","GK",1],["Mathias Dyngeland","GK",12],["Per Kristian Bråtveit","GK",23],
    ["Leo Skiri Østigård","DF",2],["Andreas Hanche-Olsen","DF",4],["Fredrik Andre Bjørkan","DF",5],
    ["Julian Ryerson","DF",3],["Kristoffer Vassbakk Ajer","DF",6],["David Møller Wolfe","DF",13],
    ["Marcus Holmgren Pedersen","DF",14],["Jesper Daland","DF",15],
    ["Martin Ødegaard","MF",10],["Sander Berge","MF",8],["Morten Thorsby","MF",7],
    ["Oscar Bobb","MF",11],["Patrick Berg","MF",16],["Hugo Vetlesen","MF",17],
    ["Erling Haaland","FW",9],["Alexander Sørloth","FW",18],["Jørgen Strand Larsen","FW",19],
    ["Johan Hove","FW",20],["Andreas Schjelderup","FW",21],["Fredrik Oppegård","FW",22],
  ],
  IRQ: [
    ["Jalal Hassan","GK",1],["Ahmed Basil","GK",12],["Fahad Talib","GK",23],
    ["Franc Putros","DF",2],["Ali Adnan","DF",3],["Saad Natiq","DF",4],
    ["Ahmad Ibrahim","DF",5],["Hussein Ali","DF",6],["Manaf Younis","DF",13],
    ["Zaid Tahseen","DF",14],["Mustafa Nadhim","DF",15],
    ["Osama Rashid","MF",8],["Amjad Attwan","MF",7],["Ali Jasim","MF",10],
    ["Mohammed Al-Baqir","MF",11],["Danilo Al-Saedi","MF",16],["Hussein Jabbar","MF",17],
    ["Aymen Hussein","FW",9],["Mohammed Ali Abboud","FW",18],["Ali Al-Hamadi","FW",19],
    ["Bassam Wael","FW",20],["Abdallah Al-Jaberi","FW",21],["Zidane Iqbal","FW",22],
  ],
  ALG: [
    ["Raïs M'Bolhi","GK",1],["Anthony Mandrea","GK",12],["Mustapha Zeghba","GK",23],
    ["Ramy Bensebaini","DF",2],["Aïssa Mandi","DF",4],["Rayan Aït-Nouri","DF",5],
    ["Ahmed Touba","DF",3],["Zineddine Belaïd","DF",6],["Kévin Guitoun","DF",13],
    ["Mohamed Amine Tougaï","DF",14],["Yasser Larouci","DF",15],
    ["Ismaël Bennacer","MF",8],["Ramiz Zerrouki","MF",7],["Sofiane Feghouli","MF",10],
    ["Houssem Aouar","MF",11],["Adem Zorgane","MF",16],["Bilal Nadir","MF",17],
    ["Islam Slimani","FW",9],["Riyad Mahrez","FW",18],["Saïd Benrahma","FW",19],
    ["Mohamed El Amine Amoura","FW",20],["Baghdad Bounedjah","FW",21],["Faris Chaïbi","FW",22],
  ],
  ARG: [
    ["Emiliano Martínez","GK",1],["Gerónimo Rulli","GK",12],["Franco Armani","GK",23],
    ["Gonzalo Montiel","DF",2],["Cristian Romero","DF",4],["Nicolás Otamendi","DF",5],
    ["Nicolás Tagliafico","DF",3],["Germán Pezzella","DF",6],["Julián Álvarez","DF",13],
    ["Nehuén Pérez","DF",14],["Juan Foyth","DF",15],
    ["Leandro Paredes","MF",8],["Rodrigo De Paul","MF",7],["Alexis Mac Allister","MF",10],
    ["Enzo Fernández","MF",11],["Exequiel Palacios","MF",16],["Guido Rodríguez","MF",17],
    ["Lionel Messi","FW",9],["Lautaro Martínez","FW",18],["Ángel Di María","FW",19],
    ["Julián Álvarez","FW",20],["Paulo Dybala","FW",21],["Nicolás González","FW",22],
  ],
  AUT: [
    ["Alexander Schlager","GK",1],["Heinz Lindner","GK",12],["Werner Hahn","GK",23],
    ["David Alaba","DF",4],["Stefan Posch","DF",5],["Philipp Lienhart","DF",3],
    ["Florian Grillitsch","DF",2],["Gernot Trauner","DF",6],["Jonas Bærum","DF",13],
    ["Kevin Danso","DF",14],["Maximilian Wöber","DF",15],
    ["Marcel Sabitzer","MF",8],["Konrad Laimer","MF",7],["Florian Kainz","MF",10],
    ["Christoph Baumgartner","MF",11],["Xaver Schlager","MF",16],["Nicolas Seiwald","MF",17],
    ["Marko Arnautović","FW",9],["Michael Gregoritsch","FW",18],["Karim Onisiwo","FW",19],
    ["Muhammed Cham","FW",20],["Dominik Fitz","FW",21],["Junior Adamu","FW",22],
  ],
  JOR: [
    ["Yazeed Abu Layla","GK",1],["Abdallah Al-Zor","GK",12],["Ahmad Al-Juaidi","GK",23],
    ["Ihsan Haddad","DF",2],["Abdallah Nasib","DF",3],["Yazan Al-Arab","DF",4],
    ["Mohammad Al-Basha","DF",5],["Suleiman Abu Theeb","DF",6],["Ahmad Al-Essawi","DF",13],
    ["Noor Al-Rawabdeh","DF",14],["Saed Al-Rosan","DF",15],
    ["Ali Al-Ajalin","MF",8],["Rajaei Ayed","MF",7],["Al-Mahdi Al-Subhi","MF",10],
    ["Mohammad Al-Mardi","MF",11],["Yasser Al-Rawashdeh","MF",16],["Mostafa Shedeifat","MF",17],
    ["Musa Al-Taamari","FW",9],["Ehsan Haddad","FW",18],["Mahmoud Al-Mardi","FW",19],
    ["Abdelatif Bahdari","FW",20],["Mohammad Aburiziq","FW",21],["Amin Al-Shanaineh","FW",22],
  ],
  POR: [
    ["Diogo Costa","GK",1],["Rui Patrício","GK",12],["José Sá","GK",23],
    ["Rúben Dias","DF",2],["António Silva","DF",4],["Nuno Mendes","DF",5],
    ["João Cancelo","DF",3],["Diogo Dalot","DF",6],["Danilo Pereira","DF",13],
    ["Pepe","DF",14],["Gonçalo Inácio","DF",15],
    ["Bruno Fernandes","MF",8],["Bernardo Silva","MF",7],["Rúben Neves","MF",10],
    ["João Palhinha","MF",11],["Vitinha","MF",16],["Matheus Nunes","MF",17],
    ["Cristiano Ronaldo","FW",9],["Rafael Leão","FW",18],["João Félix","FW",19],
    ["Diogo Jota","FW",20],["Gonçalo Ramos","FW",21],["Francisco Trincão","FW",22],
  ],
  COL: [
    ["Camilo Vargas","GK",1],["Álvaro Montero","GK",12],["Kevin Mier","GK",23],
    ["Davinson Sánchez","DF",2],["Yerry Mina","DF",4],["Juan Pablo Vargas","DF",5],
    ["Deiver Machado","DF",3],["Johan Mojica","DF",6],["Santiago Arias","DF",13],
    ["Andrés Llinás","DF",14],["Yerson Mosquera","DF",15],
    ["Wilmar Barrios","MF",8],["Mateus Uribe","MF",7],["James Rodríguez","MF",10],
    ["Jhon Arias","MF",11],["Kevin Castaño","MF",16],["Jhon Solís","MF",17],
    ["Rafael Santos Borré","FW",9],["Luis Díaz","FW",18],["Jhon Córdoba","FW",19],
    ["Juan Fernando Quintero","FW",20],["Miguel Borja","FW",21],["Yáser Asprilla","FW",22],
  ],
  UZB: [
    ["O'tkir Yusupov","GK",1],["Abduvohid Nematov","GK",12],["Bozorboev Botirali","GK",23],
    ["Odiljon Hamrobekov","DF",2],["Abdulla Abdullaev","DF",4],["Alijonov Abdulla","DF",5],
    ["Farruh Sayfiev","DF",3],["Ibrohim Xalilov","DF",6],["Jaloliddin Masharipov","DF",13],
    ["Umar Eshmurodov","DF",14],["Sherzod Nasrullaev","DF",15],
    ["O'tkir Aliyev","MF",8],["Jaloliddin Mahkamov","MF",7],["Xojimat Erkinov","MF",10],
    ["Odilikh Khamidullayev","MF",11],["Rustam Ashurmatov","MF",16],["Zafarmurod Abdurashidov","MF",17],
    ["Eldor Shomurodov","FW",9],["Azizbek Turgunboev","FW",18],["Oston Urunov","FW",19],
    ["Abbos Fayzullayev","FW",20],["Bobur Abdikholikov","FW",21],["Alisher Odilov","FW",22],
  ],
  COD: [
    ["Ley Matampi","GK",1],["Baggio Siadi","GK",12],["Kinsley Bompata","GK",23],
    ["Chancel Mbemba","DF",2],["Henock Inonga","DF",4],["Dylan Batubinsika","DF",5],
    ["Brian Nsilu","DF",3],["Joseph Mputu","DF",6],["Rocky Bushiri","DF",13],
    ["Gédéon Kalulu","DF",14],["Joris Kayembe","DF",15],
    ["Samuel Moutoussamy","MF",8],["Gaël Kakuta","MF",7],["Charles Pickel","MF",10],
    ["Grady Diangana","MF",11],["Aaron Tshibola","MF",16],["Joseph Paintsil","MF",17],
    ["Cédric Bakambu","FW",9],["Yoane Wissa","FW",18],["Théo Bongonda","FW",19],
    ["Simon Banza","FW",20],["Fiston Mayele","FW",21],["Jackson Muleka","FW",22],
  ],
  ENG: [
    ["Jordan Pickford","GK",1],["Aaron Ramsdale","GK",12],["Dean Henderson","GK",23],
    ["John Stones","DF",2],["Harry Maguire","DF",4],["Kieran Trippier","DF",5],
    ["Kyle Walker","DF",3],["Luke Shaw","DF",6],["Marc Guéhi","DF",13],
    ["Levi Colwill","DF",14],["Jarrad Branthwaite","DF",15],
    ["Declan Rice","MF",8],["Jude Bellingham","MF",7],["Mason Mount","MF",10],
    ["Conor Gallagher","MF",11],["James Maddison","MF",16],["Kobbie Mainoo","MF",17],
    ["Harry Kane","FW",9],["Bukayo Saka","FW",18],["Phil Foden","FW",19],
    ["Jack Grealish","FW",20],["Cole Palmer","FW",21],["Anthony Gordon","FW",22],
  ],
  CRO: [
    ["Dominik Livaković","GK",1],["Ivo Grbić","GK",12],["Nediljko Labrović","GK",23],
    ["Joško Gvardiol","DF",2],["Josip Šutalo","DF",4],["Borna Sosa","DF",5],
    ["Josip Juranović","DF",3],["Martin Erlić","DF",6],["Domagoj Vida","DF",13],
    ["Marin Pongračić","DF",14],["Bartol Franjić","DF",15],
    ["Luka Modrić","MF",10],["Mateo Kovačić","MF",8],["Marcelo Brozović","MF",7],
    ["Mario Pašalić","MF",11],["Lovro Majer","MF",16],["Luka Ivanušec","MF",17],
    ["Andrej Kramarić","FW",9],["Ivan Perišić","FW",18],["Bruno Petković","FW",19],
    ["Ante Budimir","FW",20],["Marko Livaja","FW",21],["Marco Pašalić","FW",22],
  ],
  GHA: [
    ["Richard Ofori","GK",1],["Lawrence Ati-Zigi","GK",12],["Abdul Manaf Nurudeen","GK",23],
    ["Andy Yiadom","DF",2],["Gideon Mensah","DF",4],["Alexander Djiku","DF",5],
    ["Daniel Amartey","DF",3],["Alidu Seidu","DF",6],["Mohammed Salisu","DF",13],
    ["Rahman Baba","DF",14],["Nicholas Opoku","DF",15],
    ["Thomas Partey","MF",8],["Mohammed Kudus","MF",7],["Joseph Paintsil","MF",10],
    ["Osman Bukari","MF",11],["Iddrisu Baba","MF",16],["Elisha Owusu","MF",17],
    ["Iñaki Williams","FW",9],["Antoine Semenyo","FW",18],["Jordan Ayew","FW",19],
    ["Ernest Nuamah","FW",20],["Kamaldeen Sulemana","FW",21],["Christopher Antwi-Adjei","FW",22],
  ],
  PAN: [
    ["Orlando Mosquera","GK",1],["César Samudio","GK",12],["Eduardo Guerra","GK",23],
    ["Michael Murillo","DF",2],["Andrés Andrade","DF",4],["Eric Davis","DF",5],
    ["José Córdoba","DF",3],["Harold Cummings","DF",6],["Ismael Díaz","DF",13],
    ["Juan Pablo Segura","DF",14],["Jorge Gutiérrez","DF",15],
    ["Aníbal Godoy","MF",8],["Adalberto Carrasquilla","MF",7],["Yoel Bárcenas","MF",10],
    ["César Yanis","MF",11],["Cristian Martínez","MF",16],["Jovani Welch","MF",17],
    ["Rolando Blackburn","FW",9],["José Fajardo","FW",18],["Ismael Díaz","FW",19],
    ["Alfredo Stephens","FW",20],["Jair Catuy","FW",21],["José Luis Rodríguez","FW",22],
  ],
};

function escape(s) {
  return "'" + s.replace(/'/g, "''") + "'";
}

let values = [];
for (const [teamId, players] of Object.entries(squads)) {
  for (const [name, pos, num] of players) {
    values.push("(" + escape(teamId) + "," + escape(name) + "," + num + "," + escape(pos) + ",false)");
  }
}

const sql = "INSERT INTO public.players (team_id, name, shirt_number, position, is_captain) VALUES\n" +
  values.join(",\n") + "\nON CONFLICT DO NOTHING;";

console.log("Inserting " + values.length + " players...");

fetch("https://api.supabase.com/v1/projects/" + ref + "/database/query", {
  method: "POST", headers: {"Authorization":"Bearer "+token,"Content-Type":"application/json"},
  body: JSON.stringify({query: sql})
}).then(r => r.status === 201 ? console.log("Jogadores inseridos com sucesso!") : r.text().then(t => console.log("ERRO:", t)));
